server:
  port: 8089
  max-http-header-size: 8999
spring:
  datasource:
    #      url: jdbc:mysql://localhost:3306/sang?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
    #      username: root
    #      password: root
    url: jdbc:mysql://hdm515540362.my3w.com:3306/hdm515540362_db?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
    username: hdm515540362
    password: imiuSOFT@100106
#    url: jdbc:mysql://localhost:3306/brush?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
#    username: root
#    password: imiusoft
#打印sql日志
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

