server:
  port: 8089
  max-http-header-size: 8192
spring:
  datasource:
    #      url: jdbc:mysql://localhost:3306/sang?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
    #      username: root
    #      password: root
    #      url: jdbc:mysql://localhost:3306/brush?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
    #      username: root
    #      password: chen
#    url: jdbc:mysql://localhost:3306/brush?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
#    username: root
#    password: imiusoft
#打印sql日志
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
