server:
    port: 8089
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/brush?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
      username: root
      password: imiusoft
#打印sql日志
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
