server:
    port: 8089
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/brush?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
      username: root
      password: imiusoft
#      url: jdbc:mysql://localhost:3306/sang?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
#      username: root
#      password: root
#      url: jdbc:mysql://localhost:3306/brush?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
#      username: root
#      password: chen
#      url: jdbc:mysql://localhost:3306/brush?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
#      username: root
#      password: chen
<<<<<<< HEAD
=======
#      url: jdbc:mysql://hdm515540362.my3w.com:3306/hdm515540362_db?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
#      username: hdm515540362
#      password: imiuSOFT@100106
      url: jdbc:mysql://47.98.201.181:3306/brush?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true
      username: root
      password: chen0221
>>>>>>> ff3cd1f61f2b82c88baa667a944a880297b833af
#打印sql日志
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
